# Generated by Django 3.1.5 on 2021-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
